### ISSUE TITLE
Service throws Index Out of Range error on cloud platforms

### ISSUE THREAD

**Issue by aaronlaver** [CrunchyData/pg_featureserv#107] opened 2022-03-31 22:07 UTC
I've been trying to run both pg_featureserv and pg_tileserv using AWS ECS and GCP Cloud Run services. pg_tileserv hasn't had any issues whatsoever, but every time I spin up a pg_featureserv docker container I am met with a "Service Unavailable" screen in the browser. The logs return the following errors in this order:

The request failed because either the HTTP response was malformed or connection to the instance had an error. Additional troubleshooting documentation can be found at: https://cloud.google.com/run/docs/troubleshooting#timeout-503

2022-03-31T22:02:04.471444Z2022/03/31 22:02:04 http: panic serving 169.254.8.129:35297: runtime error: index out of range [0] with length 0 goroutine 7 [running]: net/http.(*conn).serve.func1(0xc00007a140) /opt/hostedtoolcache/go/1.16.14/x64/src/net/http/server.go:1805 +0x153 panic(0xa930e0, 0xc00007c0d8) /opt/hostedtoolcache/go/1.16.14/x64/src/runtime/panic.go:971 +0x499 net/http.(*timeoutHandler).ServeHTTP(0xc0001c9240, 0xba8cd8, 0xc0002a0000, 0xc00007e500) /opt/hostedtoolcache/go/1.16.14/x64/src/net/http/server.go:3302 +0x949 net/http.serverHandler.ServeHTTP(0xc00012a380, 0xba8cd8, 0xc0002a0000, 0xc00007e500) /opt/hostedtoolcache/go/1.16.14/x64/src/net/http/server.go:2868 +0xa3 net/http.(*conn).serve(0xc00007a140, 0xbaa5c0, 0xc0000661c0) /opt/hostedtoolcache/go/1.16.14/x64/src/net/http/server.go:1933 +0x8cd created by net/http.(*Server).Serve /opt/hostedtoolcache/go/1.16.14/x64/src/net/http/server.go:2994 +0x39b

Just wondering if this is a use case that's generally supported or not.

**Comment by dr-jts** [comment] 2022-03-31 22:25
Can you provide more information about the configuration you are using to run the container?

**Comment by aaronlaver** [comment] 2022-04-01 02:33
Thanks for your response. Disclaimer: I'm a relative newbie to all of this. 

At present, where the errors were received, I am running on Google Cloud Run. One thing I noticed is that it generates an HTTPS end point at the end of every container that's spun up. 

Here's what I've tried so far (all return the same errors):
`docker run -d --name ppl_pgfeatureserv -e DATABASE_URL=postgres://*database URL* -e PGFS_SERVER_HTTPSPORT=9001 -e PGFS_SERVER_CORSORIGINS="*" -p 9000:9000 pramsey/pg_featureserv:latest`

`docker run -d --name ppl_pgfeatureserv -e DATABASE_URL=*database URL* -e PGFS_SERVER_HTTPSPORT=9001 -p 9000:9000 pramsey/pg_featureserv:latest`

`docker run -d --name ppl_pgfeatureserv1 -e DATABASE_URL=*database URL* -p 9000:9000 pramsey/pg_featureserv:latest`

For comparison's sake, the "out of the box" command that worked for tileserv is as follows:
`docker run -d --name ppl_pgtile -e DATABASE_URL=postgres://places:gZSnpCv7@35.232.212.158/places -p 7800:7800 pramsey/pg_tileserv`

Here's of a URL that's produced by GCP whenever the image has been committed, tagged, pushed, and deployed as a container. [](https://*repository name*-y36wbtgbvq-uc.a.run.app/)

As far as the Cloud Run configuration, you can specify many things... but really I've only been offering the port number (9000) and letting all traffic in until everything gets sorted out.

**Comment by dr-jts** [comment] 2022-04-01 16:36
Thanks - this is enough info for me to try and reproduce this error. 

My first thought is that it's a defect in the way the default configuration is handled - but it could be something else, which might be harder to debug.

**Comment by dr-jts** [comment] 2022-04-01 16:49
Why are you specifying the HTTPS port?  That won't get used unless you also specify `TlsServerCertificateFile` and `TlsServerPrivateKeyFile`.   I don't think that's the cause of the error, but it's better to simplify the run as much as possible.

**Comment by aaronlaver** [comment] 2022-04-01 17:13
I tried specifying the https port, cors origins, etc., later on after the "default" method (the 3rd configuration above) failed. I figured it was a long shot...but a shot nonetheless. Regardless, for the purposes of what I want to run the service for...it's not a necessity of my use case. I was just trying to get it to function as tileserv was.

**Comment by aaronlaver** [comment] 2022-04-01 17:33
Sure thing. I've also attached the logs in csv format. 

`2022-04-01 13:24:49.525 EDT
time="2022-04-01T17:24:49Z" level=info msg="169.254.8.129:25648 GET /\n"
Error
2022-04-01 13:24:49.527 EDT
2022/04/01 17:24:49 http: panic serving 169.254.8.129:25648: runtime error: index out of range [0] with length 0 goroutine 11 [running]: net/http.(*conn).serve.func1(0xc000290d20) /opt/hostedtoolcache/go/1.16.14/x64/src/net/http/server.go:1805 +0x153 panic(0xa930e0, 0xc00002bef0) /opt/hostedtoolcache/go/1.16.14/x64/src/runtime/panic.go:971 +0x499 net/http.(*timeoutHandler).ServeHTTP(0xc00021b3c0, 0xba8cd8, 0xc00017c460, 0xc000282400) /opt/hostedtoolcache/go/1.16.14/x64/src/net/http/server.go:3302 +0x949 net/http.serverHandler.ServeHTTP(0xc00017c380, 0xba8cd8, 0xc00017c460, 0xc000282400) /opt/hostedtoolcache/go/1.16.14/x64/src/net/http/server.go:2868 +0xa3 net/http.(*conn).serve(0xc000290d20, 0xbaa5c0, 0xc00021b600) /opt/hostedtoolcache/go/1.16.14/x64/src/net/http/server.go:1933 +0x8cd created by net/http.(*Server).Serve /opt/hostedtoolcache/go/1.16.14/x64/src/net/http/server.go:2994 +0x39b
Default
2022-04-01 13:24:49.527 EDT
time="2022-04-01T17:24:49Z" level=debug msg="---- Request cancelled by client after 912.72µs"
Error
2022-04-01 13:24:49.529 EDT
GET
503
972 B
8 ms
Chrome 99.0.4844.84
https://*servicename*
[downloaded-logs-20220401-132810.csv](https://github.com/CrunchyData/pg_featureserv/files/8399803/downloaded-logs-20220401-132810.csv)
-y36wbtgbvq-uc.a.run.app/`

**Comment by dr-jts** [comment] 2022-04-01 18:10
Thanks, but I still can't reproduce the error.

Is the `https` request generated by you?  Or does that happen automatically?  What happens if you use a `http` request?

**Comment by aaronlaver** [comment] 2022-04-01 18:17
Bummer. Thanks for trying. The https request is automatic and at least on GCP non-negotiable. When using an HTTP request it reverts back to HTTPS. I could probably work out and pass in a default cert though if you're confident that it's the source of the error.

**Comment by dr-jts** [comment] 2022-04-01 18:35
Nope, not at all confident that the missing cert is the cause of the error.  A missing cert doesn't cause an error in my test environment (but it is quite different to GCP).  It's interesting that `pg_tileserv` works, since I think it has the same requirement for a cert.  Is it serving `https` requests with no problem?

**Comment by fw8** [comment] 2022-07-06 14:03
This issue is closed but not resolved... Just want to mention that I have the same issue as @aaronlaver running the container in Google Cloud Run. Also pg_tileserver works seamlessly in this environment! It would be really helpful to fix this problem...

**Comment by dr-jts** [comment] 2022-07-06 18:34
This should be fixed by https://github.com/CrunchyData/pg_featureserv/commit/f35fe8a8815c556c22833fe1c641c8607230f7cb

**Comment by dr-jts** [comment] 2022-07-06 18:38
@aaronlaver are you able to check that this issue is resolved?

**Comment by aaronlaver** [comment] 2022-08-16 20:43
Works great now as specified by others. Thanks!

**Closed** 2022-08-16 20:43 UTC
Labels: bug

**Comment by jjhi11** [comment] 2023-10-18 20:04
> This issue is closed but not resolved... Just want to mention that I have the same issue as @aaronlaver running the container in Google Cloud Run. Also pg_tileserver works seamlessly in this environment! It would be really helpful to fix this problem...

@fw8 Florian
I am having a problem deploying to cloud run myself. Did you use the CLI to deploy the image?
